version: "3"
services:
  app:
    container_name: front-app
    build: 
      context: .
    image: ${DOCKER_USER_ID}/devops-calendar
  production:
    image: ${DOCKER_USER_ID}/devops-calendar:${BUILD_NUMBER}
    ports:
        - 3000:3000
    volumes: 
        - .:/app
