version: "3" 
services: 
  app: 
    build: ./frontend
    image: ${DOCKER_USER_ID}/devops-calendar 
  production: 
    image: ${DOCKER_USER_ID}/devops-calendar:${BUILD_NUMBER} 
    volumes: 
      - .:/app
    command: npm run serve
    ports: 
      - 3000:3000
